[common]
overwrite = true
project=CYWeb
module=Wxpay


########################### 配置文件设置 ###########################

## 生产配置文件， key:value,key:value
[conf]
MAX_PN:50,DEFAULT_RN:20


########################### 控制器Controller设置 ###########################
#所有控制器
[controller]
controllers = Canyin


### 买单
# 控制器的函数
[CanyinController]
functions=index|main|coupons|pay|cancel|state
extends=H5BaseController

[CanyinController.index]
desc=实际买单页面
type=get
author=zhaoye
funcType =public
paramNum = 1
param0 = kdtId|kdt_id|Noo|店铺Id
tpl=H5/Payment/Index

[CanyinController.main]
desc=买单页面-跳转实际买单url
type=get
paramNum = 1
param0=kdtId|kdt_id|Noo|店铺Id


[CanyinController.coupons]
desc=获取买家优惠券列表
type=get
paramNum = 4
param0=kdtId|kdt_id|Noo|店铺Id
param1=buyerId|buyer_id|Noo|buyerId|env
param2=fansId|fans_id|Noo|fansId|env
param3=fansType|fans_type|Noo|fansType|env
return={"code":0,"msg":"h5\/payment::Coupons","data":{"couponsList":[{"disabled":false,"couponName":"\u5fc5\u987b\u6ee15\u5143","couponDiscount":"4rx57b95","id":89090,"couponTime":"2017-06-01 16:14:42\u81f32017-06-30 16:14:42","couponMeet":500,"couponCash":100},{"disabled":false,"couponName":"1\u5143","couponDiscount":"f5eisstr","id":89004,"couponTime":"2017-06-01 12:02:42\u81f32017-06-30 12:02:42","couponMeet":0,"couponCash":100}]}}

[CanyinController.pay]
desc=提交支付
type=get
paramNum = 13
param0=kdtId|kdt_id|Noo|店铺Id
param1=price|price|Noo|买单总金额 (单位:分)
param2=orderId|orderId|0|需要支付的订单
param3=discountPrice|discountPrice|Noo|优惠后实付金额 (单位:分)
param4=selectCoupon|selectCoupon|0|优惠券编号
param5=buyer|buyer|Noo|buyer|env
param6=youzanFansId|youzan_fans_id|Noo|youzanFansId|env
param7=fansNickname|fans_nickname|Noo|fansNickname|env
param8=fansType|fans_type|Noo|fansType|env
param9=payType|payType|Noo|payType,支付方式(wxpay/alipay)
param10=platform|platform|Noo|platform|env
param11=clientIp|remoteIp|Noo|客户端IP|context
param12=buyerId|buyerId|Noo|buyerId


[CanyinController.cancel]
desc=取消付款
type=get
paramNum = 2
param0=kdtId|kdt_id|Noo|店铺Id
param1=orderId|orderId|Noo|支付单id
return={}


[CanyinController.state]
desc=支付状态
type=get
paramNum = 2
param0=orderId|orderId|Noo|支付单id
param1=buyer|buyer|Noo|buyer|env
return={}


[CanyinController.result]
desc=支付结果页面
type=get
